# -*- coding: utf-8 -*-
"""Put an 'Open in Colab' badge at the top of every notebook, and keep it right.

    python tools/add_colab_badges.py --check    # report only, exit 1 if wrong
    python tools/add_colab_badges.py            # insert or repair

WHY THIS IS A SCRIPT AND NOT A ONE-TIME EDIT

The badge URL contains the repository name, the branch, and the notebook's own
path. All three change: the repo was renamed once already in planning, notebooks
get renamed for their subject, and folders move between parts. A badge that
points at a path which no longer exists **fails as a 404 on Colab**, which reads
to a student as "the course material is broken" rather than "a link is stale" --
and nothing in the repository reports it, because the file it names is missing
on GitHub rather than here.

So the badge is generated from the notebook's actual path, and `--check` makes a
wrong one a test failure instead of a student's dead end.

THE BADGE IS A STANDARD REQUIREMENT, NOT A CONVENIENCE

Part 5: "One click, no install. Assume a student with a browser, a free account,
and no software. In practice: a public repo, a hosted-notebook badge, and a
first cell that installs pinned dependencies plus the package itself."

Two of those three are not true yet -- the repository is private, and the setup
cells are session 3's work -- so the badges resolve only once it goes public.
They are added now because the alternative is adding twelve of them later and
missing one.
"""
import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB_DIR = ROOT / "notebooks"

REPO = "sear-labs/energy-system-modeling"
BRANCH = "main"

BADGE_RE = re.compile(
    r"^\s*\[!\[[^\]]*\]\(https://colab\.research\.google\.com/assets/colab-badge\.svg\)\]"
    r"\([^)]*\)\s*$",
    re.M,
)


def badge_for(rel_posix):
    """The badge markdown for a notebook at `rel_posix` (relative to the repo root).

    Alt text is 'Open in Colab' rather than 'badge' or empty: Part 3 requires
    link text that says where it goes, and a screen reader announces the alt
    text of a linked image as the link.
    """
    url = f"https://colab.research.google.com/github/{REPO}/blob/{BRANCH}/{rel_posix}"
    return (
        "[![Open in Colab]"
        "(https://colab.research.google.com/assets/colab-badge.svg)]"
        f"({url})"
    )


def notebooks():
    return sorted(
        p for p in NB_DIR.rglob("*.ipynb") if ".ipynb_checkpoints" not in str(p)
    )


# The README carries the same badges in a table, matching `advopt-lithiumsc`,
# the sibling series. Two places holding the same twelve URLs is exactly the
# duplication that drifts, so the table is GENERATED between these markers
# rather than hand-maintained, and --check verifies it.
TABLE_START = "<!-- NOTEBOOK-TABLE:START - generated by tools/add_colab_badges.py -->"
TABLE_END = "<!-- NOTEBOOK-TABLE:END -->"

README = ROOT / "README.md"


def first_heading(path):
    """The notebook's own H1, which is what a reader recognises it by."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    for cell in nb["cells"]:
        if cell["cell_type"] != "markdown":
            continue
        for line in "".join(cell["source"]).splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    return path.stem


def build_table():
    rows = [
        "| Notebook | Title | |",
        "|---|---|---|",
    ]
    part = None
    for p in notebooks():
        rel = p.relative_to(ROOT).as_posix()
        if p.parent.name != part:
            part = p.parent.name
            rows.append(f"| **`{part}/`** | | |")
        badge = (
            "[![Colab](https://colab.research.google.com/assets/colab-badge.svg)]"
            f"(https://colab.research.google.com/github/{REPO}/blob/{BRANCH}/{rel})"
        )
        rows.append(f"| `{p.name}` | {first_heading(p)} | {badge} |")
    return "\n".join(rows)


def sync_readme(check):
    text = README.read_text(encoding="utf-8")
    if TABLE_START not in text or TABLE_END not in text:
        return ["README.md has no NOTEBOOK-TABLE markers"]
    head, rest = text.split(TABLE_START, 1)
    _old, tail = rest.split(TABLE_END, 1)
    want = f"{TABLE_START}\n\n{build_table()}\n\n{TABLE_END}"
    new = head + want + tail
    if new == text:
        return []
    if not check:
        README.write_text(new, encoding="utf-8", newline="\n")
    return ["README.md notebook table is out of date"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report without writing; exit 1 if any badge is missing or wrong")
    args = ap.parse_args()

    problems, changed = [], []
    for path in notebooks():
        rel = path.relative_to(ROOT).as_posix()
        want = badge_for(rel)
        nb = json.loads(path.read_text(encoding="utf-8"))

        cells = nb["cells"]
        if not cells or cells[0]["cell_type"] != "markdown":
            problems.append(f"{rel}: first cell is not markdown; cannot place a badge")
            continue

        src = "".join(cells[0]["source"])
        found = BADGE_RE.search(src)

        if found and found.group(0).strip() == want:
            continue  # already correct

        if found:
            problems.append(f"{rel}: badge present but points elsewhere")
            new_src = BADGE_RE.sub(want, src, count=1)
        else:
            problems.append(f"{rel}: no badge")
            new_src = want + "\n\n" + src.lstrip("\n")

        if not args.check:
            # keep nbformat's list-of-lines shape, so the diff stays line-wise
            lines = new_src.splitlines(keepends=True)
            cells[0]["source"] = lines
            path.write_text(
                json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
            )
            changed.append(rel)

    problems += sync_readme(args.check)

    total = len(notebooks())
    if args.check:
        if problems:
            print(f"{len(problems)} of {total} notebooks have a missing or wrong badge:")
            for p in problems:
                print("   ", p)
            return 1
        print(f"all {total} notebooks carry the right Colab badge")
        return 0

    for c in changed:
        print("  badged", c)
    print(f"\n{len(changed)} of {total} notebooks updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
