# -*- coding: utf-8 -*-
"""Give every notebook the same setup cell, and keep it that way.

    python tools/sync_setup_cells.py --check    # report only, exit 1 if any differ
    python tools/sync_setup_cells.py            # write it into every notebook

WHY THIS IS GENERATED RATHER THAN WRITTEN TWELVE TIMES

The house rule is "one setup cell in every notebook -- patch them everywhere or
nowhere". Twelve hand-maintained copies of the same twenty lines is the exact
shape that drifts: a fix lands in the three you were looking at, and the other
nine keep the bug. This makes the cell a generated artifact with one source, so
"everywhere or nowhere" is enforced instead of remembered.

The only per-notebook part is the dependency list, which is derived from what
the notebook actually imports and pinned from requirements.txt -- so a notebook
cannot install something it does not need, or need something it does not
install. That second half is not hypothetical: three notebooks defaulted to
Gurobi and never installed gurobipy, and passed locally because the authoring
machine had it.

WHAT THE CELL DOES, AND WHY IN THAT ORDER

    1. install pinned dependencies      Colab has pandas and matplotlib and
                                        nothing else here
    2. get the repository               `pip install git+...` ships the package
                                        but NOT data/ -- see the standard, Part
                                        6 -- so it has to be a clone
    3. chdir into the notebook's folder so ../../data and ../../src resolve the
                                        same way they do in a local clone
    4. say what it did                  a setup cell that prints nothing is a
                                        setup cell nobody can debug

Step 2 fails with an explanation rather than a stack trace, because the one way
it fails is worth naming: a clone of a PRIVATE repository 404s, and so does a
raw file URL. Public is the prerequisite for a student running this at all.

IT ABSORBS THE NOTEBOOK'S OWN IMPORT CELL, ON PURPOSE

The first version of this tool inserted the setup cell above whatever followed
the title. In nine of twelve notebooks that was the import block, and a code
cell directly below another code cell is an orphan under Part 3 -- so the tool
fixed one check by breaking another. Giving `import numpy as np` a markdown
heading of its own would be ceremony; they are one setup step, so they become
one cell. Everything below END_MARKER is the notebook's own and survives
regeneration untouched.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB_DIR = ROOT / "notebooks"
REQS = ROOT / "requirements.txt"

REPO_URL = "https://github.com/sear-labs/energy-system-modeling"

MARKER = "# --- setup: generated by tools/sync_setup_cells.py"
END_MARKER = "# --- end generated setup; the notebook's own imports follow ---"

# What Colab already has. Installing these wastes a minute and risks a resolver
# fight with the preinstalled versions.
COLAB_STOCK = {"pandas", "numpy", "matplotlib", "scipy", "networkx", "requests",
               "plotly", "ipywidgets", "openpyxl"}

# import name -> distribution name
DIST = {"gurobipy": "gurobipy", "pypsa": "pypsa", "pulp": "PuLP", "highspy": "highspy"}


def pins_from_requirements():
    """Read the pins from requirements.txt rather than restating them here.

    Part 6: a guard that restates the list it checks against is a second copy
    that nothing compares, so the guard against drift drifts first.
    """
    out = {}
    for line in REQS.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r"^([A-Za-z0-9_.\-]+)\s*(.*)$", line)
        if m:
            out[m.group(1).lower()] = line
    return out


def deps_for(path, pins):
    """Pinned installs this notebook needs: what it imports, minus Colab stock."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    src = "\n".join("".join(c["source"]) for c in nb["cells"]
                    if c["cell_type"] == "code")
    imported = {m.group(1) for m in
                re.finditer(r"^\s*(?:import|from)\s+([A-Za-z_]\w*)", src, re.M)}
    need = {n for n in imported if n in DIST and n not in COLAB_STOCK}
    # highspy is never imported by name -- it is the solver PyPSA calls -- so it
    # rides along with pypsa rather than being detected.
    if "pypsa" in need:
        need.add("highspy")
    return [pins[DIST[n].lower()] for n in sorted(need) if DIST[n].lower() in pins]


# A literal backslash-n, emitted INTO the generated source rather than
# interpreted here. Built from chr(92) because writing it directly has been
# mangled three times by an intermediate shell on this machine.
NL = chr(92) + "n"


def generated_block(path, deps):
    folder = path.parent.name
    pin_list = ", ".join('"' + d + '"' for d in deps)
    return f'''{MARKER} -- do not edit here, edit that
# The same cell in every notebook in this series. It installs what Colab does
# not have, fetches the repository so that data/ and src/ are present, and moves
# into this notebook's own folder so the relative paths below resolve.
import os
import subprocess
import sys
from pathlib import Path

REPO_URL = "{REPO_URL}"
REPO_NAME = REPO_URL.rstrip("/").split("/")[-1]
NOTEBOOK_DIR = "notebooks/{folder}"

# Pinned, per Part 1 rule 3: an unpinned install will one day pull a major
# version with a changed API and either break or silently alter the answer.
PINS = [{pin_list}]

if "google.colab" in sys.modules:
    if PINS:
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", *PINS], check=True)
    # An ABSOLUTE base, so re-running this cell is safe. Colab's "Run all" is
    # commonly run twice, and a relative check would look for the clone inside
    # the folder it had already moved into -- cloning a second copy nested one
    # level down, then working from the wrong one.
    BASE = Path("/content") if Path("/content").is_dir() else Path.home()
    REPO_DIR = BASE / REPO_NAME
    if not REPO_DIR.exists():
        cloned = subprocess.run(
            ["git", "clone", "--depth", "1", REPO_URL, str(REPO_DIR)],
            capture_output=True, text=True)
        if cloned.returncode != 0:
            raise SystemExit(
                "Could not clone " + REPO_URL + "{NL}"
                + (cloned.stderr or "").strip() + "{NL}{NL}"
                "If that says 'not found', the repository is still private.{NL}"
                "A raw file URL fails the same way, so there is no way around{NL}"
                "it: it has to be public before a student can run this.")
    os.chdir(REPO_DIR / NOTEBOOK_DIR)
elif Path.cwd().name != Path(NOTEBOOK_DIR).name:
    raise SystemExit(
        "Run this notebook from its own folder (" + NOTEBOOK_DIR + "),{NL}"
        "so that ../../src and ../../data resolve.")

sys.path.insert(0, str(Path.cwd().parents[1] / "src"))
print("working directory:", Path.cwd().name)

{END_MARKER}
'''


HEADING_SOURCE = [
    "## Setup\n",
    "\n",
    "One cell, the same in every notebook here: it installs what Colab does not "
    "have, fetches this repository so `data/` and `src/` are present, and moves "
    "into this notebook's own folder so the relative paths below resolve. The "
    "notebook's own imports follow in the same cell.\n",
]


def heading_cell():
    return {"cell_type": "markdown", "metadata": {}, "source": list(HEADING_SOURCE)}


def notebooks():
    return sorted(p for p in NB_DIR.rglob("*.ipynb")
                  if ".ipynb_checkpoints" not in str(p))


def strip_pip_lines(text):
    """Remove `!pip install` / `%pip install` lines.

    The generated PINS list installs the same packages with version bounds, so
    an unpinned magic anywhere in this cell would install twice AND fail the
    audit's deps-pinned check. Applied to the preserved half as well as to
    newly absorbed content, because pipeline_transport had one that arrived
    before this rule existed.
    """
    return "\n".join(l for l in text.splitlines()
                     if not l.strip().startswith(("!pip install", "%pip install")))


def split_cell(cell):
    """(generated half, the notebook's own half) of an existing setup cell."""
    body = "".join(cell.get("source", []))
    if END_MARKER not in body:
        return body, ""
    head, tail = body.split(END_MARKER, 1)
    return head + END_MARKER + "\n", strip_pip_lines(tail)


def as_source(text):
    lines = text.split("\n")
    return [l + "\n" for l in lines[:-1]] + ([lines[-1]] if lines[-1] else [])


def is_import_only(cell):
    """True if every meaningful line is an import, a comment, or a pip magic.

    Deliberately strict: a single assignment or call means the cell is doing
    something a reader is meant to see, and it keeps its own place.
    """
    body = "".join(cell.get("source", []))
    if MARKER in body:
        return False
    lines = [l.strip() for l in body.splitlines() if l.strip()]
    if not lines:
        return False
    for line in lines:
        if line.startswith(("#", "!", "%")):
            continue
        if re.match(r"^(import|from)\s+\w", line):
            continue
        return False
    return True


def is_bare_pip(cell):
    if cell["cell_type"] != "code":
        return False
    body = "".join(cell["source"]).strip()
    if MARKER in body or not body.startswith("!pip install"):
        return False
    return all(l.strip().startswith("!pip install") or not l.strip()
               for l in body.splitlines())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    pins = pins_from_requirements()
    problems, changed = [], []

    for path in notebooks():
        rel = path.relative_to(ROOT).as_posix()
        want = generated_block(path, deps_for(path, pins))
        nb = json.loads(path.read_text(encoding="utf-8"))
        cells = nb["cells"]

        idx = next((i for i, c in enumerate(cells)
                    if c["cell_type"] == "code" and MARKER in "".join(c["source"])), None)

        cell_ok = idx is not None and split_cell(cells[idx])[0] == want
        # An unpinned install anywhere in the setup cell -- including in the
        # half this tool preserves -- is a finding, so it has to trigger a
        # rewrite rather than being silently carried forward.
        if idx is not None:
            raw_tail = "".join(cells[idx]["source"]).split(END_MARKER, 1)
            if len(raw_tail) == 2 and ("!pip install" in raw_tail[1]
                                       or "%pip install" in raw_tail[1]):
                cell_ok = False
        heading_ok = (idx is not None and idx > 0
                      and cells[idx - 1]["cell_type"] == "markdown")
        merged_ok = (idx is not None
                     and (idx + 1 >= len(cells) or cells[idx + 1]["cell_type"] != "code"))

        if cell_ok and heading_ok and merged_ok:
            continue

        why = ("setup cell missing" if idx is None
               else "setup cell differs" if not cell_ok
               else "no markdown heading above the setup cell" if not heading_ok
               else "a code cell sits directly below the setup cell (orphan)")
        problems.append(rel + ": " + why)
        if args.check:
            continue

        if idx is None:
            new = {"cell_type": "code", "execution_count": None, "metadata": {},
                   "outputs": [], "source": as_source(want)}
            cells.insert(1, heading_cell())
            cells.insert(2, new)
            at = 2
        else:
            _head, tail = split_cell(cells[idx])
            cells[idx]["source"] = as_source(want + tail)
            cells[idx]["outputs"] = []
            cells[idx]["execution_count"] = None
            at = idx
            if not heading_ok:
                cells.insert(idx, heading_cell())
                at = idx + 1

        # Absorb orphaned IMPORT-SHAPED code cells sitting directly below.
        #
        # Bounded to import-shaped cells on purpose. Merging arbitrary code
        # cells would trade an orphan for a violation of "one idea per cell" and
        # of the cell-length limit -- fixing one check by breaking two. An
        # import block is not an idea; it is the rest of the setup.
        #
        # Some of these were orphans before this tool existed (pipeline_transport
        # had four), so this repairs rather than creates.
        while (at + 1 < len(cells)
               and cells[at + 1]["cell_type"] == "code"
               and is_import_only(cells[at + 1])):
            body = "".join(cells[at]["source"])
            if not body.endswith("\n"):
                body += "\n"
            # Strip `!pip install` lines out of what is absorbed. PINS above
            # already installs the same packages WITH version bounds, so keeping
            # the old line would both install twice and leave an unpinned
            # install in the notebook -- which is what happened to
            # pipeline_transport, whose install sat under a comment and so was
            # not a bare-pip cell the removal below would catch.
            absorbed = "".join(cells[at + 1]["source"])
            absorbed = "\n".join(l for l in absorbed.splitlines()
                                 if not l.strip().startswith(("!pip install",
                                                              "%pip install")))
            body += "\n" + absorbed
            cells[at]["source"] = as_source(body)
            cells[at]["outputs"] = []
            cells[at]["execution_count"] = None
            del cells[at + 1]

        # drop any bare `!pip install` cell: unpinned, and the generated block
        # installs the same things with version bounds
        nb["cells"] = [c for c in cells if not is_bare_pip(c)]

        path.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n",
                        encoding="utf-8")
        changed.append(rel)

    total = len(notebooks())
    if args.check:
        if problems:
            print(f"{len(problems)} of {total} notebooks have a stale setup cell:")
            for p in problems:
                print("   ", p)
            return 1
        print(f"all {total} notebooks carry the current setup cell")
        return 0

    for c in changed:
        print("  setup cell ->", c)
    print(f"\n{len(changed)} of {total} notebooks updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
